### PR TITLE
Add version

### PR DESCRIPTION
**Pull request by boced66**
For the compatibility with the future version of HASS
#20

### CODE REVIEW

**Comment by larserhardsen** [comment]
Please approve this PR, as it fixes the problem that the integration won't start in HA 2021.6.0

**Comment by anvarit** [comment]
@filipvh can you approve the build from @boced66 ? 
HA users updating to 2021.6.0 have currently issues that the integration won't load anymore.

**Comment by boced66** [comment]
You can just add the line in the file.
It's not à proper solution but It's work. 😉

**Comment by nielsvissers** [comment]
even though i added the line, i still can't install the integration
i'm running 2021.6.3

**Comment by SonnyBBQ** [comment]
> even though i added the line, i still can't install the integration
> i'm running 2021.6.3

I"m not on 2021.6 yet, but I have updated my manifest file and no longer getting the log notifications.  Can you post your manifest.json , so we can check?

**Comment by boced66** [comment]
Hello @nielsvissers ,
Can you verify that there is a comma at the end of the previous line?

```
  "codeowners": ["@filipvh"],
  "version": "2021.4.1"
```

**Comment by nielsvissers** [comment]
apparently I had to reboot the host multiple times, I can now add the integration

**Comment by filipvh** [comment]
For HACS I've pre-released this as 1.6.0-beta1

Can someone validate it works?

**Comment by SonnyBBQ** [comment]
> For HACS I've pre-released this as 1.6.0-beta1
> 
> Can someone validate it works?

Thanks Filip.  Just updated to 1.6.0-beta 1 and it works.

**Comment by filipvh** [comment]
I'll release 1.6.0 then

**Pull request merged**
