### PR TITLE
add thermostats

### PR DESCRIPTION
**Pull request by joleys**

### CODE REVIEW

**Comment by filipvh** [comment]
@joleys I merged your changes on nhc2-coco and published it as version 1.4.0

**Comment by filipvh** [comment]
@joleys  If I'm not mistaken, you need to bump nhc2-coco to 1.4.1
Then I can merge the code and put out a new release 😄

**Comment by joleys** [comment]
@filipvh This way?

**Comment by filipvh** [comment]
@joleys 
a did a beta release, so it can be tested through HACS. Do you have HACS, I don't have thermostats... :)
https://github.com/filipvh/hass-nhc2/releases/tag/1.7.0-beta1

**Pull request merged**
